import SideBarContainer from '@/components/sideBarContainer'
import './globals.css'
import { Roboto } from '@next/font/google'
import ContextProvider from '@/context/AppContext'

const roboto = Roboto({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['100', '300', '400', '500', '700']
})

export const metadata = {
  title: 'ArsianDev',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }) => {
  return (
    <html className={roboto.className} lang='en'>
      <body className='flex w-screen h-screen flex-row'>
        <ContextProvider>
          <div className='h-max lg:w-2/6'>
            <SideBarContainer />
          </div>
          <div className='flex w-screen h-screen bg-black-1 lg:w-4/6'>{children}</div>
        </ContextProvider>
      </body>
    </html>
  )
}

export default RootLayout
